# Generated by Django 3.2.9 on 2022-07-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Пред')),
            ],
            options={
                'verbose_name': 'Инфо',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Пушкина 46/3', max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=False, verbose_name='На главную')),
                ('image', models.ImageField(upload_to='Address/%Y/%m/%d', verbose_name='Фото')),
                ('map_place', models.URLField(verbose_name='Ссылка на карту')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл. адрес')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('is_pub', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл.Адрес')),
                ('subject', models.CharField(max_length=100, verbose_name='Причина')),
                ('message', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Reclame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(help_text='Максимум 254 символ!', max_length=255, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=False, verbose_name='На главную')),
                ('image', models.ImageField(help_text='1920*1001', upload_to='Hello/%Y/%m/%d', verbose_name='Фото')),
                ('is_pub', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Рекламы',
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='30%-70% скидка на все', max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=False, verbose_name='На главную')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Sell/%Y/%m/%d', verbose_name='Фото')),
                ('is_pub', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='Team/%Y/%m/%d', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
                ('site', models.URLField(verbose_name='Ссылка на соц сеть')),
                ('position', models.CharField(choices=[('DIRECTOR', 'Директор'), ('MANAGER', 'Менеджер'), ('ADMINISTRATOR', 'Администратор'), ('DESIGNER', 'Дизайнер'), ('SELLER', 'Продавец')], default='WEB DEVELOPER', max_length=50, verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Команда',
            },
        ),
    ]
