# Generated by Django 3.2.9 on 2022-08-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_blog_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='like',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Лайк'),
        ),
    ]
