# Generated by Django 3.2.9 on 2022-07-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл.Адрес')),
                ('cart', models.ManyToManyField(blank=True, related_name='cart', to='product.Product', verbose_name='Корзина')),
                ('wishlist', models.ManyToManyField(blank=True, related_name='wishlist', to='product.Product', verbose_name='Избранное')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
