# Generated by Django 3.2.9 on 2022-08-20 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_gender'),
        ('customers', '0002_myuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.CharField(choices=[('CASH', 'Наличка'), ('CARD', 'Карта')], default='CARD', max_length=4, verbose_name='Платеж')),
                ('service', models.BooleanField(default=True, verbose_name='Доставка')),
                ('address', models.CharField(max_length=80, verbose_name='Адрес')),
                ('total_item', models.PositiveIntegerField(default=1, verbose_name='Кол-во')),
                ('ord_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.myuser', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='ItemOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Кол-во')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.order', verbose_name='Заказчик')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
