# Generated by Django 3.2.9 on 2022-08-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_itemorders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_item',
            field=models.PositiveIntegerField(default=1, verbose_name='Сумма'),
        ),
    ]
