# Generated by Django 3.2.9 on 2022-08-25 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20220820_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorders',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='itemorders',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.order', verbose_name='Заказчик'),
        ),
    ]
