# Generated by Django 3.2.9 on 2022-08-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20220825_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_products', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во продуктов')),
                ('amount_categories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во категорий')),
                ('amount_sub_categories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во саб категорий')),
                ('amount_customers', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во клиентов')),
                ('amount_blogs', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во блогов')),
                ('amount_comments', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во комметариев')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_draft',
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Номер счета'),
        ),
    ]
