# Generated by Django 3.2.9 on 2022-08-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20220825_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка'),
        ),
    ]
