# Generated by Django 3.2.9 on 2022-08-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorders',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка'),
        ),
    ]
