# Generated by Django 3.2.9 on 2022-08-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20220827_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default='static/images/blank-profile-picture-973460__340.webp', upload_to='Customer/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
